# Generated by Django 4.2.5 on 2023-09-12 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='creae_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
