# Generated by Django 4.2.5 on 2023-09-12 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todomodel_created_at_todomodel_creae_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='creae_at',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
